//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OQM10P_HFT_2021221.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OQM10P_HFT_2021221.Data.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{\&quot;Id\&quot;:1,\&quot;Name\&quot;:\&quot;Renelle Bedham\&quot;,\&quot;Email\&quot;:\&quot;rbedham0@g.co\&quot;,\&quot;Sex\&quot;:\&quot;1\&quot;,\&quot;Username\&quot;:\&quot;rbedham0\&quot;,\&quot;Position\&quot;:\&quot;1\&quot;}, {\&quot;Id\&quot;:2,\&quot;Name\&quot;:\&quot;Sheena Rapps\&quot;,\&quot;Email\&quot;:\&quot;srapps1@webmd.com\&quot;,\&quot;Sex\&quot;:\&quot;1\&quot;,\&quot;Username\&quot;:\&quot;srapps1\&quot;,\&quot;Position\&quot;:\&quot;1\&quot;}, {\&quot;Id\&quot;:3,\&quot;Name\&quot;:\&quot;Charlton Lebourn\&quot;,\&quot;Email\&quot;:\&quot;clebourn2@washingtonpost.com\&quot;,\&quot;Sex\&quot;:\&quot;1\&quot;,\&quot;Username\&quot;:\&quot;clebourn2\&quot;,\&quot;Position\&quot;:\&quot;2\&quot;}, {\&quot;Id\&quot;:4,\&quot;Name\&quot;:\&quot;Susette Ridel\&quot;,\&quot;Email\&quot;:\&quot;sridel3@ibm.com\&quot;,\&quot;Sex\&quot;:\&quot;1\&quot;,\&quot;Username\&quot;:\&quot;sridel3\&quot;,\&quot;Pos [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string userJson {
            get {
                return ResourceManager.GetString("userJson", resourceCulture);
            }
        }
    }
}
